// Generated by dts-bundle v0.7.2
// Dependencies for this module:
//   ../fatina

import { IPlugin } from 'fatina';
import { IControl } from 'fatina';
import { ITicker } from 'fatina';

export function Get(): IPlugin;
export interface IPluginAnimator {
    AnimatorManager: AnimatorManager;
    TickerManager: TickerManager;
}
export class FatinaPluginAnimator implements IPlugin {
    readonly name: string;
    readonly TickerManager: any;
    readonly AnimatorManager: any;
    Init(fatina: any): void;
}

export class AnimatorManager {
    readonly Animations: string[];
    readonly Labels: string[];
    constructor(plugin: FatinaPluginAnimator);
    Register(name: string, onCreate: (object: any, params?: any) => IControl, tickerName?: string): AnimatorManager;
    Instantiate(name: string, object: any, params?: any): IControl;
    AddAnimatorTo(obj: any): Animator;
}

export class TickerManager {
    constructor(plugin: IPluginAnimator);
    Get(name: string): ITicker;
    PauseAll(name: string): void;
    ResumeAll(name: string): void;
    KillAll(name: string): void;
}

export interface IAnimationParams {
    group?: string;
    unstoppable?: boolean;
    finalValue?: boolean;
    next?: string;
}
export class Animator {
    animations: {
        [id: string]: IControl;
    };
    current: {
        [id: string]: IControl | undefined;
    };
    groups: string[];
    constructor(obj: any, animatorManager: AnimatorManager);
    AddAnimation(name: string, animationName: string, options?: IAnimationParams | any, params?: any): Animator;
    AddCustomAnimation(name: string, options: IAnimationParams | any, tween: IControl): Animator;
    OnStartAll(name: string, cb: () => void): Animator;
    OnStart(name: string, cb: () => void): Animator;
    OnCompleteAll(name: string, cb: () => void): Animator;
    OnComplete(name: string, cb: () => void): Animator;
    Play(name: string, onComplete?: () => void): void;
    Pause(group?: string): void;
    PauseAll(): void;
    Resume(group?: string): void;
    ResumeAll(): void;
    Stop(group?: string): void;
    StopAll(): void;
    Destroy(): void;
}

