// Generated by dts-bundle v0.7.3

export let plugin: any;
export { EasingType as Easing };
export let time: number;
export function Elapsed(): number;
export function MainTicker(): ITicker;
export function AddListenerCreated(cb: (control: IControl) => void): void;
export function RemoveListenerCreated(cb: (control: IControl) => void): void;
export function Init(disableAutoTick?: boolean): boolean;
export function SetTimescale(scale: number): void;
export function Pause(): void;
export function Resume(): void;
export function SetLog(level: Log): void;
export function SetSafe(isSafe: boolean): void;
export function Destroy(): void;
export function Update(timestamp: number): any;
export function Tween(obj: any, properties: string[]): ITween;
export function Sequence(): ISequence;
export function Delay(duration: number): IPlayable;
export function SetTimeout(fn: () => void, duration: number): IPlayable;
export function SetInterval(fn: () => void, duration: number): IPlayable;
export function Ticker(): ITicker;
export function LoadPlugin(newPlugin: IPlugin): void;

export enum Log {
    None = 0,
    Info = 1,
    Debug = 2,
}

export interface IControl {
    elapsed: number;
    duration: number;
    state: State;
    Start(): void;
    Pause(): void;
    Resume(): void;
    Kill(): void;
    Reset(): void;
    Skip(finalValue?: boolean): void;
    IsIdle(): boolean;
    IsRunning(): boolean;
    IsFinished(): boolean;
    IsPaused(): boolean;
}

export interface IPlayable extends IControl {
    state: State;
    SetParent(ticker: ITicker): IPlayable;
    Start(): IPlayable;
    SetLoop(loop: number): IPlayable;
    SetSafe(safe: boolean): IPlayable;
    SetLog(level: Log): IPlayable;
    OnStart(cb: () => void): IPlayable;
    OnRestart(cb: () => void): IPlayable;
    OnUpdate(cb: (dt: number, progress: number) => void): IPlayable;
    OnKilled(cb: () => void): IPlayable;
    OnComplete(cb: () => void): IPlayable;
}

export interface IPlugin {
    readonly name: string;
    Init(fatina: any): void;
}

export interface ISequence extends IControl {
    Count: number;
    Start(): ISequence;
    SetParent(ticker: ITicker): ISequence;
    SetTimescale(scale: number): ISequence;
    SetLoop(loop: number): ISequence;
    SetSafe(safe: boolean): ISequence;
    SetLog(level: Log): ISequence;
    Append(tween: ITween | ISequence): ISequence;
    AppendCallback(cb: () => void): ISequence;
    AppendInterval(duration: number): ISequence;
    Prepend(tween: ITween | ISequence): ISequence;
    PrependCallback(cb: () => void): ISequence;
    PrependInterval(duration: number): ISequence;
    Join(tween: ITween | ISequence): ISequence;
    OnStart(cb: () => void): ISequence;
    OnRestart(cb: () => void): ISequence;
    OnStepStart(cb: (tween: ITween | IPlayable) => void): ISequence;
    OnStepEnd(cb: (index: ITween | IPlayable) => void): ISequence;
    OnUpdate(cb: (dt: number, progress: number) => void): ISequence;
    OnKilled(cb: () => void): ISequence;
    OnComplete(cb: () => void): ISequence;
}

export interface ITicker extends IControl {
    AddTickListener(cb: (dt: number) => void): void;
    RemoveTickListener(cb: (dt: number) => void): void;
    SetTimescale(scale: number): void;
}

export interface ITween extends IControl {
    Init(object: any, properties: string[]): void;
    Start(): ITween;
    From(from: any): ITween;
    To(to: any, duration: number): ITween;
    Modify(diff: any, updateTo: boolean): void;
    Reverse(): void;
    Yoyo(time: number): ITween;
    SetParent(ticker: ITicker): ITween;
    SetLoop(loop: number): ITween;
    SetSteps(steps: number): ITween;
    SetRelative(relative: boolean): ITween;
    SetEasing(type: EasingType | string): ITween;
    SetTimescale(scale: number): ITween;
    ToSequence(): ISequence;
    SetSafe(safe: boolean): ITween;
    SetLog(level: Log): ITween;
    OnStart(cb: () => void): ITween;
    OnUpdate(cb: (dt: number, progress: number) => void): ITween;
    OnRestart(cb: () => void): ITween;
    OnKilled(cb: () => void): ITween;
    OnComplete(cb: () => void): ITween;
}

export enum EasingType {
    Linear = "linear",
    InQuad = "inQuad",
    OutQuad = "outQuad",
    InOutQuad = "inOutQuad",
    InCubic = "inCubic",
    OutCubic = "outCubic",
    InOutCubic = "inOutCubic",
    InQuart = "inQuart",
    OutQuart = "outQuart",
    InOutQuart = "inOutQuart",
    InSine = "inSine",
    OutSine = "outSine",
    InOutSine = "inOutSine",
    InCirc = "inCirc",
    OutCirc = "outCirc",
    InOutCirc = "inOutCirc",
    InQuint = "inQuint",
    OutQuint = "outQuint",
    InOutQuint = "inOutQuint",
    InExponential = "inExponential",
    OutExponential = "outExponential",
    InOutExponential = "inOutExponential",
    InElastic = "inElastic",
    OutElastic = "outElastic",
    InOutElastic = "inOutElastic",
    InBack = "inBack",
    OutBack = "outBack",
    InOutBack = "inOutBack",
    InBounce = "inBounce",
    OutBounce = "outBounce",
    InOutBounce = "inOutBounce",
}

export enum State {
    Idle = 0,
    Run = 1,
    Pause = 2,
    Finished = 3,
    Killed = 4,
}

